#!/usr/bin/env bash
set -euo pipefail

ENVIRONMENT="${1:-staging}"
LOCATION="${AZURE_LOCATION:-eastus}"
POSTGRES_ADMIN_LOGIN="${AZURE_POSTGRES_ADMIN_LOGIN:-hostedsymphony}"
BASE_URL_DEFAULT="https://hosted-symphony-${ENVIRONMENT}.example.internal"
HOSTED_BASE_URL="${HOSTED_SYMPHONY_BASE_URL:-$BASE_URL_DEFAULT}"
RESOURCE_GROUP_PREFIX="${AZURE_RESOURCE_GROUP_PREFIX:-hosted-symphony}"
RESOURCE_GROUP_DEFAULT="${RESOURCE_GROUP_PREFIX}-${ENVIRONMENT}-rg"

if ! command -v az >/dev/null 2>&1; then
  echo "Azure CLI is required." >&2
  exit 1
fi

ACCOUNT_JSON="$(az account show --output json)"
SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID:-$(printf '%s' "$ACCOUNT_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])')}"
TENANT_ID="$(printf '%s' "$ACCOUNT_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["tenantId"])')"
USER_NAME="$(printf '%s' "$ACCOUNT_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["user"]["name"])')"
RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-$RESOURCE_GROUP_DEFAULT}"

sanitize_name() {
  python3 - "$1" "$2" <<'PY'
import re
import sys

value = re.sub(r'[^a-z0-9-]', '-', sys.argv[1].lower()).strip('-')
value = re.sub(r'-+', '-', value)
limit = int(sys.argv[2])
print(value[:limit].rstrip('-'))
PY
}

sanitize_storage_name() {
  python3 - "$1" "$2" <<'PY'
import re
import sys

value = re.sub(r'[^a-z0-9]', '', sys.argv[1].lower())
limit = int(sys.argv[2])
print((value[:limit] or 'hostedsymphony')[:limit])
PY
}

ACR_NAME="${AZURE_CONTAINER_REGISTRY_NAME:-$(sanitize_storage_name "hostedsymphony${ENVIRONMENT}acr" 50)}"
STORAGE_ACCOUNT_NAME="${AZURE_STORAGE_ACCOUNT_NAME:-$(sanitize_storage_name "hostedsymphony${ENVIRONMENT}sa" 24)}"
KEY_VAULT_NAME="${AZURE_KEY_VAULT_NAME:-$(sanitize_name "hosted-symphony-${ENVIRONMENT}-kv" 24)}"
POSTGRES_SERVER_NAME="${AZURE_POSTGRES_SERVER_NAME:-$(sanitize_name "hosted-symphony-${ENVIRONMENT}-pg" 63)}"

ENV_FILE=".env.azure.local"

az account set --subscription "$SUBSCRIPTION_ID" >/dev/null
az configure --defaults group="$RESOURCE_GROUP" location="$LOCATION" >/dev/null

cat > "$ENV_FILE" <<EOF
# Generated by infra/azure/scripts/bootstrap-local.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Azure CLI user: $USER_NAME
HOSTED_SYMPHONY_CLOUD_PROVIDER=azure
HOSTED_SYMPHONY_ENVIRONMENT=$ENVIRONMENT
HOSTED_SYMPHONY_BASE_URL=$HOSTED_BASE_URL
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
AZURE_TENANT_ID=$TENANT_ID
AZURE_RESOURCE_GROUP=$RESOURCE_GROUP
AZURE_LOCATION=$LOCATION
AZURE_CONTAINER_REGISTRY_NAME=$ACR_NAME
AZURE_STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME
AZURE_KEY_VAULT_NAME=$KEY_VAULT_NAME
AZURE_POSTGRES_SERVER_NAME=$POSTGRES_SERVER_NAME
AZURE_POSTGRES_ADMIN_LOGIN=$POSTGRES_ADMIN_LOGIN

# Fill these before deploying
HOSTED_SYMPHONY_SERVICE_TOKEN=
SYMPHONY_WORKER_EVENT_SECRET=
GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY=
OPENAI_API_KEY=
AZURE_POSTGRES_ADMIN_PASSWORD=
EOF

echo "Azure defaults configured:"
echo "  subscription: $SUBSCRIPTION_ID"
echo "  resource group: $RESOURCE_GROUP"
echo "  location: $LOCATION"
echo
echo "Wrote $ENV_FILE with Azure deployment names and secret placeholders."
echo "Next steps:"
echo "  1. Fill the secret placeholders in $ENV_FILE"
echo "  2. source $ENV_FILE"
echo "  3. az group create --name \"$RESOURCE_GROUP\" --location \"$LOCATION\""
echo "  4. az deployment group create --resource-group \"$RESOURCE_GROUP\" --template-file infra/azure/main.bicep --parameters @infra/azure/parameters/${ENVIRONMENT}.parameters.json --parameters controlPlaneBaseUrl=\"$HOSTED_BASE_URL\" containerRegistryName=\"$ACR_NAME\" storageAccountName=\"$STORAGE_ACCOUNT_NAME\" keyVaultName=\"$KEY_VAULT_NAME\" postgresServerName=\"$POSTGRES_SERVER_NAME\" postgresAdminLogin=\"$POSTGRES_ADMIN_LOGIN\" controlPlaneImage=\"${ACR_NAME}.azurecr.io/hosted-symphony-control-plane:latest\" workerImage=\"${ACR_NAME}.azurecr.io/hosted-symphony-worker:latest\" postgresAdminPassword=\"\$AZURE_POSTGRES_ADMIN_PASSWORD\" serviceToken=\"\$HOSTED_SYMPHONY_SERVICE_TOKEN\" workerEventSecret=\"\$SYMPHONY_WORKER_EVENT_SECRET\" githubAppId=\"\$GITHUB_APP_ID\" githubAppPrivateKey=\"\$GITHUB_APP_PRIVATE_KEY\" openAiApiKey=\"\$OPENAI_API_KEY\""
